apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: shivanium/webpage

---
apiVersion: v1
kind: Service
metadata:
  name: mywebpage
spec:
  type: NodePort
  selector:
    app: webpage  
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
